# Generated by Django 3.2.6 on 2021-08-23 20:21

from django.db import migrations, models
import django.db.models.deletion
import jables.models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.CharField(default=jables.models.generate, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(default=tracker.models.generate_clan_code, max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='clan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.clan'),
        ),
    ]
